name: Build HackMD App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
        
    - name: Install dependencies
      run: |
        brew update
        brew install create-dmg || true
        
    - name: List Xcode project structure
      run: |
        ls -la
        find . -name "*.xcodeproj" -type d
      
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        xcodebuild -project HackMD.xcodeproj -scheme "HackMD" -configuration Release -derivedDataPath build DEVELOPMENT_TEAM="" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        
    - name: Create DMG
      run: |
        mkdir -p build/Release
        cp -r build/Build/Products/Release/HackMD.app build/Release/
        create-dmg \
          --volname "HackMD for macOS" \
          --volicon "HackMD/Assets.xcassets/AppIcon.appiconset/app_icon_512.png" \
          --background "HackMD/Assets.xcassets/dmg-background.imageset/background.png" \
          --window-pos 200 120 \
          --window-size 800 450 \
          --icon-size 100 \
          --icon "HackMD.app" 200 190 \
          --hide-extension "HackMD.app" \
          --app-drop-link 600 185 \
          --no-internet-enable \
          "HackMD.dmg" \
          "build/Release/" \
        || cp -r build/Release/HackMD.app HackMD.app && zip -r HackMD.zip HackMD.app
        
    - name: Upload application as artifact
      uses: actions/upload-artifact@v4
      with:
        name: HackMD-app
        path: |
          HackMD.dmg
          HackMD.zip
        
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./HackMD.dmg
        asset_name: HackMD.dmg
        asset_content_type: application/x-apple-diskimage
